/* tartrazine.h generated by valac 0.34.4, the Vala compiler, do not modify */


#ifndef __TARTRAZINE_H__
#define __TARTRAZINE_H__

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS


#define TARTRAZINE_TYPE_ROBOT_POISON (tartrazine_robot_poison_get_type ())
#define TARTRAZINE_ROBOT_POISON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TARTRAZINE_TYPE_ROBOT_POISON, TartrazineRobotPoison))
#define TARTRAZINE_ROBOT_POISON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TARTRAZINE_TYPE_ROBOT_POISON, TartrazineRobotPoisonClass))
#define TARTRAZINE_IS_ROBOT_POISON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TARTRAZINE_TYPE_ROBOT_POISON))
#define TARTRAZINE_IS_ROBOT_POISON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TARTRAZINE_TYPE_ROBOT_POISON))
#define TARTRAZINE_ROBOT_POISON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TARTRAZINE_TYPE_ROBOT_POISON, TartrazineRobotPoisonClass))

typedef struct _TartrazineRobotPoison TartrazineRobotPoison;
typedef struct _TartrazineRobotPoisonClass TartrazineRobotPoisonClass;
typedef struct _TartrazineRobotPoisonPrivate TartrazineRobotPoisonPrivate;

#define TARTRAZINE_ROBOT_POISON_TYPE_TOOLS (tartrazine_robot_poison_tools_get_type ())
#define TARTRAZINE_ROBOT_POISON_TOOLS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TARTRAZINE_ROBOT_POISON_TYPE_TOOLS, TartrazineRobotPoisonTools))
#define TARTRAZINE_ROBOT_POISON_TOOLS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TARTRAZINE_ROBOT_POISON_TYPE_TOOLS, TartrazineRobotPoisonToolsClass))
#define TARTRAZINE_ROBOT_POISON_IS_TOOLS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TARTRAZINE_ROBOT_POISON_TYPE_TOOLS))
#define TARTRAZINE_ROBOT_POISON_IS_TOOLS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TARTRAZINE_ROBOT_POISON_TYPE_TOOLS))
#define TARTRAZINE_ROBOT_POISON_TOOLS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TARTRAZINE_ROBOT_POISON_TYPE_TOOLS, TartrazineRobotPoisonToolsClass))

typedef struct _TartrazineRobotPoisonTools TartrazineRobotPoisonTools;
typedef struct _TartrazineRobotPoisonToolsClass TartrazineRobotPoisonToolsClass;
typedef struct _TartrazineRobotPoisonToolsPrivate TartrazineRobotPoisonToolsPrivate;

struct _TartrazineRobotPoison {
	GObject parent_instance;
	TartrazineRobotPoisonPrivate * priv;
};

struct _TartrazineRobotPoisonClass {
	GObjectClass parent_class;
};

struct _TartrazineRobotPoisonTools {
	GTypeInstance parent_instance;
	volatile int ref_count;
	TartrazineRobotPoisonToolsPrivate * priv;
};

struct _TartrazineRobotPoisonToolsClass {
	GTypeClass parent_class;
	void (*finalize) (TartrazineRobotPoisonTools *self);
};


GType tartrazine_robot_poison_get_type (void) G_GNUC_CONST;
TartrazineRobotPoison* tartrazine_robot_poison_new_WithAppParams (const gchar* app, const gchar* host, const gchar* igroup);
TartrazineRobotPoison* tartrazine_robot_poison_construct_WithAppParams (GType object_type, const gchar* app, const gchar* host, const gchar* igroup);
void tartrazine_robot_poison_SaveSet (TartrazineRobotPoison* self);
void tartrazine_robot_poison_FriendSendMessage (TartrazineRobotPoison* self, guint32 friendNumber, const gchar* message);
gboolean tartrazine_robot_poison_SaveData (TartrazineRobotPoison* self);
gboolean tartrazine_robot_poison_Online (TartrazineRobotPoison* self);
void tartrazine_robot_poison_main (void);
TartrazineRobotPoison* tartrazine_robot_poison_new (void);
TartrazineRobotPoison* tartrazine_robot_poison_construct (GType object_type);
gpointer tartrazine_robot_poison_tools_ref (gpointer instance);
void tartrazine_robot_poison_tools_unref (gpointer instance);
GParamSpec* tartrazine_robot_poison_param_spec_tools (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void tartrazine_robot_poison_value_set_tools (GValue* value, gpointer v_object);
void tartrazine_robot_poison_value_take_tools (GValue* value, gpointer v_object);
gpointer tartrazine_robot_poison_value_get_tools (const GValue* value);
GType tartrazine_robot_poison_tools_get_type (void) G_GNUC_CONST;
guint8* tartrazine_robot_poison_tools_hex2bin (const gchar* s, int* result_length1);
gchar* tartrazine_robot_poison_tools_bin2hex (guint8* bin, int bin_length1);
gchar* tartrazine_robot_poison_tools_bin2nullterm (guint8* data, int data_length1);
gchar* tartrazine_robot_poison_tools_arr2str (guint8* array, int array_length1);
TartrazineRobotPoisonTools* tartrazine_robot_poison_tools_new (void);
TartrazineRobotPoisonTools* tartrazine_robot_poison_tools_construct (GType object_type);


G_END_DECLS

#endif
